### ISSUE TITLE
Enhancement: Add Multiple run commands

### ISSUE THREAD

**Issue by YouveGotMeowxy** [magicmark/composerize#138]
I love Compozerize!

Currently it only allows adding a single `docker run` line to convert; I have a bunch of HTPC containers that I have setup only using docker run commands that I really would love to be able to paste into the composerize box, separated line by line, and then have it converted into a single docker-compose.

Like this:

![image](https://user-images.githubusercontent.com/39491297/68256548-1f14b800-fff6-11e9-9c43-1b8c63a6dbd5.png)

**Comment by magicmark** [comment]
This a great idea, would love to see this 👍

**Comment by sharevb** [comment]
Hi, this is solved by my PR https://github.com/magicmark/composerize/pull/571 deployed at https://deploy-preview-571--composerize.netlify.app/
