### ISSUE TITLE
Only the last env is processed

### ISSUE THREAD

**Issue by kassanmoor** [magicmark/composerize#14]
If I have a run with several -e, only the last one is processed. example:

docker run --restart=always -h master --name prep9_db -d -p 5432:5432 -e dbname=odoo -e dbpass=aSecurePass psql
 only dbpass is displayed

**Comment by magicmark** [comment]
@kassanmoor I cannot reproduce. Have you tried with the latest version? (or clearing browser cache?)

```
╔═ mark@macbook: /tmp/tmp.N9FsyW83mM
╚═ $ node_modules/.bin/composerize docker run --restart=always -h master --name prep9_db -d -p 5432:5432 -e dbname=odoo -e dbpass=aSecurePass psql
version: 3
services:
    psql:
        restart: always
        container_name: prep9_db
        ports:
            - '5432:5432'
        environment:
            - dbname=odoo
            - dbpass=aSecurePass
        image: psql
```

**Comment by kassanmoor** [comment]
clear browse cache did the trick, thanks!
