### ISSUE TITLE
bad parses private  docker registry images

### ISSUE THREAD

**Issue by kassanmoor** [magicmark/composerize#15]
When I use an image form a private registry, for example docker run --restart=always --privileged --name jatdb -d -p 27017:27017 -p 28017:28017 -e MONGODB_PASS="somepass" -v ~/jat/mongodata:/data/db registry.cloud.local/js/mongo 

the service name is set to js instead of registry.cloud.local/js/mongo

**Comment by sharevb** [comment]
Hi, this is solved by my PR https://github.com/magicmark/composerize/pull/571 deployed at https://deploy-preview-571--composerize.netlify.app/
