### ISSUE TITLE
Sensitive info

### ISSUE THREAD

**Issue by maltokyo** [magicmark/composerize#180]
Hi @magicmark 
I pasted inadvertently some sensitive info on https://composerize.com

I am wondering if you keep logs of what was posted there, and if you could please delete them.  I apologise for this request.  I tried to contact you via other channels, email etc, but could not find. 
Thank you
Mal

**Comment by magicmark** [comment]
@maltokyo the web application is hosted as a static site on netlify - there’s no extra logs on my side of things. I’ll dig into the netlify side of things a bit more.

Apologies - feel free to dm me on Twitter (@mark_larah) and we can continue the discussion there.
