### ISSUE TITLE
version should be between apostrophes  ''

### ISSUE THREAD

**Issue by kassanmoor** [magicmark/composerize#22]
when you directly copy the resulting compose file and try to run error `Version in "./docker-compose.yml" is invalid - it should be a string.` is raised due lack of apostrophes in the version section

**Comment by magicmark** [comment]
Thanks for the report @kassanmoor! Would you like to try taking a stab at a fix for this?

**Comment by kassanmoor** [comment]
I want @magicmark but I guees I need some instructions, I have the repo, create my branch and do `npm install` but get npm WARN composerize@1.0.1 No repository field, did not touch node before, do you have a hackme/build me or readme instructions somewhere?

**Comment by magicmark** [comment]
Closing as fixed with the latest version (1.0.4) :)
