### ISSUE TITLE
support docker create input

### ISSUE THREAD

**Issue by moo-im-a-cow** [magicmark/composerize#26]
**Do you want to request a *feature* or report a *bug*?**
FEATURE
Docker create is exactly the same as docker run except that it doesnt start the container.
(docker run = docker create && docker start)
**Please provide a sample input docker run command**
```
docker create -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro --restart always --log-opt max-size=1g nginx
```

**What is the current output?***
```
NO OUTPUT
```

**What is the expected/desired output?**
```
version: 3
services:
    nginx:
        ports:
            - '80:80'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
        restart: always
        logging:
            options:
                max-size: 1g
        image: nginx```

**Comment by sharevb** [comment]
Seems supported right now

**Comment by sharevb** [comment]
Hi, this is solved by my PR https://github.com/magicmark/composerize/pull/571 deployed at https://deploy-preview-571--composerize.netlify.app/
