### ISSUE TITLE
[Enhancement] Show warning when there are unidentified arguments

### ISSUE THREAD

**Issue by yxliang01** [magicmark/composerize#31]
Having this feature would make composerize more usable. So that, the user knows exactly what arguments are not being translated and can be added manually later.

Thanks

**Comment by sharevb** [comment]
Hi, this is solved by being added to comments in front for generated compose file by my PR https://github.com/magicmark/composerize/pull/571 deployed at https://deploy-preview-571--composerize.netlify.app/
