### ISSUE TITLE
Use Github Releases and Semantic Versioning

### ISSUE THREAD

**Issue by DarkGigaByte** [magicmark/composerize#4]
http://semver.org/

**Comment by magicmark** [comment]
Thanks for the issue!

I'm doing some experimentation in this repo. tl;dr is that that the compoerize logic has been split into a [seperate npm package](https://github.com/magicmark/composerize/blob/master/packages/composerize/package.json). It uses semver (still an alpha version), but I haven't set up github releases yet.

Let's add travis to this repo to set up tags and do this.

**Comment by magicmark** [comment]
I've just released a [v1.0.0](https://github.com/magicmark/composerize/releases/tag/v1.0.0).

I've also done a bit of housekeeping:
- split the website into a seperate repo (https://github.com/magicmark/composerize-website).
- set up travis auto-deploys to npm

Closing. Let me know if you have any more thoughts :)
