### ISSUE TITLE
Update https://composerize.com with the latest code

### ISSUE THREAD

**Issue by alesrebec** [magicmark/composerize#52]
Issues #22 and #49 can be fixed if the code on the website https://composerize.com is updated to the latest one using docker version in quotes.
[3f37b35](https://github.com/magicmark/composerize/commit/3f37b356915137d9803534226cde88fae6396114)

Any love for this @magicmark?

**Comment by magicmark** [comment]
Apologies, it's taken me a few weekends to get round to giving this project some love. Fixed the package deployment in this repo, we're now on the latest version on the website.

https://composerize.com/
