### ISSUE TITLE
--log-opt max-size=10m --log-opt max-file=5 not converting to object

### ISSUE THREAD

**Issue by hayden-t** [magicmark/composerize#525]
if you put this in you end up with:

```
        logging:
            options: 'max-size=10m,max-file=5'
```

but docker complains it should be an object

`logging.options contains an invalid type, it should be an object`

should be 

```
        logging:
            options: 
                {'max-size':'10m', 'max-file':'5'}

```

**Comment by azumukupoe** [comment]
```
options:
  max-size: "200k"
  max-file: "10"
```
https://docs.docker.com/compose/compose-file/compose-file-v3/#logging

**Comment by hayden-t** [comment]
ok, thanks, will try that next time

**Comment by sharevb** [comment]
Hi, this is solved by my PR https://github.com/magicmark/composerize/pull/571 deployed at https://deploy-preview-571--composerize.netlify.app/
