### ISSUE TITLE
Will the website ever be updated?

### ISSUE THREAD

**Issue by STaRDoGG** [magicmark/composerize#57]
I noticed the code has support for the --net/--network param, but the website doesn't; is the site ever going to get the latest stuff?

Also, curious to know if anything gets logged on the site? i.e. do all the conversions people do on the site get stored anywhere?

**Comment by magicmark** [comment]
Apologies, it's taken me a few weekends to get round to giving this project some love. Fixed the package deployment in this repo, we're now on the latest version on the website.

https://composerize.com/

> Also, curious to know if anything gets logged on the site? i.e. do all the conversions people do on the site get stored anywhere?

Nope, nothing gets stored (other than your browser cache)

The website is deployed from this repo https://github.com/magicmark/composerize-website, so you can poke about at what it's doing :)
