### ISSUE TITLE
fails to convert init script

### ISSUE THREAD

**Issue by mm7979** [magicmark/composerize#572]
Input:
--rm -e INFLUXDB_HTTP_AUTH_ENABLED=true -e INFLUXDB_ADMIN_USER=admin -e INFLUXDB_ADMIN_PASSWORD=admin123 -v /var/lib/influxdb:/var/lib/influxdb -v /etc/influxdb/scripts:/docker-entrypoint-initdb.d  influxdb /init-influxdb.sh

Output:
version: '3.3'
services:
    init-influxdb.sh:
        environment:
            - INFLUXDB_HTTP_AUTH_ENABLED=true
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin123
        volumes:
            - '/var/lib/influxdb:/var/lib/influxdb'
            - '/etc/influxdb/scripts:/docker-entrypoint-initdb.d'
        image: /init-influxdb.sh

**Comment by sharevb** [comment]
Hi, this is solved by my PR deployed at https://deploy-preview-571--composerize.netlify.app/
