### ISSUE TITLE
support opposite direction

### ISSUE THREAD

**Issue by patrickleet** [magicmark/composerize#92]
Would be great if this tool could work the opposite direction as well - given a docker-compose file, what would be the docker commands?

**Comment by magicmark** [comment]
Love the idea! I wonder if there's any prior art here?

**Comment by YouveGotMeowxy** [comment]
+1

**Comment by ream88** [comment]
Was also looking for this. docker-compose and all its python deps really bring my Raspberry Pi Zero  to a crawl. The only (very outdated) thing I found is this: https://github.com/alexhumphreys/dc2dr

**Comment by ream88** [comment]
Just implemented https://github.com/ream88/compose-docker/tree/master for me

**Comment by magicmark** [comment]
Very cool, thanks for the link!

I just registered decomposerize.com (i'm thinking maybe we could mirror sites like [urldecoder.org](urldecoder.org)/[urlencoder.org](urlencoder.org))

@anishnath let me know if you're interested and i'll happily transfer this domain to you :) (bonus points if you wanted to collaborate on a shared ui)

**Comment by sharevb** [comment]
Just released the reverse of composerize : [Decomposerize](https://decomposerize.netlify.app/)

**Comment by sharevb** [comment]
It is now operational as https://www.decomposerize.com

**Comment by sharevb** [comment]
Done right now
